version: '3'

services:
  backend:
    build: backend/
    container_name: backend
    ports: 
      - 9880:9880
    networks:
      - deploy_network

  frontend:
    build: frontend/
    container_name: frontend
    depends_on:
      - backend
    ports: 
      - 7860:7860
    networks:
      - deploy_network

networks:
  deploy_network:
    driver: bridge
